// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSerialNames() {
  return window['go']['main']['App']['GetSerialNames']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PortClose() {
  return window['go']['main']['App']['PortClose']();
}

export function PortOpen(arg1, arg2, arg3) {
  return window['go']['main']['App']['PortOpen'](arg1, arg2, arg3);
}
