// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSerialNames():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function IsConnected():Promise<boolean>;

export function PortClose():Promise<void>;

export function PortOpen(arg1:string,arg2:number,arg3:number):Promise<void>;
